# ripta-server:
#   image: ripta-server
#   environment:
#     - MAPS_API_KEY=$MAPS_API_KEY
#     - MONGO_ADDR=mongo
#   ports:
#     - "8080:8080"
#     - "9001:9001"
#   links:
#     - mongo
postgres:
  image: mdillon/postgis
  ports:
    - "5432:5432"
