apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: postgres
  name: postgres-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - image: mdillon/postgis
        name: postgres
        env:
        - name: PGDATA
          value: /data/db/postgres
        ports:
        - name: postgres
          containerPort: 5432
          hostPort: 5432
        volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /data/db
      volumes:
        - name: postgres-persistent-storage
          gcePersistentDisk:
            pdName: ripta-server-postgres-disk
            fsType: ext4
