apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ripta-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: production
        tier: backend
    spec:
      containers:
      - name: ripta-server
        image: gcr.io/riptabot/ripta-server:1.0.1
        env:
        - name: DB_ADDR
          value: postgresql://postgres@postgres/ripta?sslmode=disable
        - name: MAPS_API_KEY
          value: AIzaSyBLkfEHV6n0MIevqnKgHAbFem6CxGZd9Iw
        ports:
        - containerPort: 8080
        - containerPort: 9001
